// @ts-nocheck
/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/nqtr vite plugin. Do not edit manually.
declare module "@drincs/nqtr/registries" {
    interface NqtrActivityIds {
        "bed": never;
        "order_product": never;
        "take_product": never;
    }
    interface NqtrCommitmentIds {
        "alice_sleep": never;
        "alice_go_school": never;
        "alice_smokes": never;
        "alice_quest_talk": never;
    }
    interface NqtrLocationIds {
        "mc_home": never;
        "gym": never;
        "school": never;
    }
    interface NqtrMapIds {
        "main_map": never;
        "nightcity_map": never;
    }
    interface NqtrQuestIds {
        "aliceQuest": never;
    }
    interface NqtrRoomIds {
        "mc_room": never;
        "alice_room": never;
        "ann_room": never;
        "bathroom": never;
        "lounge": never;
        "terrace": never;
        "gym_room": never;
        "class_room": never;
    }
}
export {};
