// @ts-nocheck
/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/nqtr vite plugin. Do not edit manually.

export const nqtrActivityIds = ["bed","order_product","take_product"] as const;
export const nqtrCommitmentIds = ["alice_sleep","alice_go_school","alice_smokes","alice_quest_talk"] as const;
export const nqtrLocationIds = ["mc_home","gym","school"] as const;
export const nqtrMapIds = ["main_map","nightcity_map"] as const;
export const nqtrQuestIds = ["aliceQuest"] as const;
export const nqtrRoomIds = ["mc_room","alice_room","ann_room","bathroom","lounge","terrace","gym_room","class_room"] as const;

export const nqtrActivityIdsEnum = { "bed": "bed", "order_product": "order_product", "take_product": "take_product" } as const;
export const nqtrCommitmentIdsEnum = { "alice_sleep": "alice_sleep", "alice_go_school": "alice_go_school", "alice_smokes": "alice_smokes", "alice_quest_talk": "alice_quest_talk" } as const;
export const nqtrLocationIdsEnum = { "mc_home": "mc_home", "gym": "gym", "school": "school" } as const;
export const nqtrMapIdsEnum = { "main_map": "main_map", "nightcity_map": "nightcity_map" } as const;
export const nqtrQuestIdsEnum = { "aliceQuest": "aliceQuest" } as const;
export const nqtrRoomIdsEnum = { "mc_room": "mc_room", "alice_room": "alice_room", "ann_room": "ann_room", "bathroom": "bathroom", "lounge": "lounge", "terrace": "terrace", "gym_room": "gym_room", "class_room": "class_room" } as const;

declare module "@drincs/nqtr/registries" {
    interface NqtrActivityIds {
        "bed": never;
        "order_product": never;
        "take_product": never;
    }
    interface NqtrCommitmentIds {
        "alice_sleep": never;
        "alice_go_school": never;
        "alice_smokes": never;
        "alice_quest_talk": never;
    }
    interface NqtrLocationIds {
        "mc_home": never;
        "gym": never;
        "school": never;
    }
    interface NqtrMapIds {
        "main_map": never;
        "nightcity_map": never;
    }
    interface NqtrQuestIds {
        "aliceQuest": never;
    }
    interface NqtrRoomIds {
        "mc_room": never;
        "alice_room": never;
        "ann_room": never;
        "bathroom": never;
        "lounge": never;
        "terrace": never;
        "gym_room": never;
        "class_room": never;
    }
}
