/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
declare module "@drincs/pixi-vn/characters" {
    interface PixivnCharacterIds {
        "mc": never;
        "alice": never;
    }
}
declare module "@drincs/pixi-vn/narration" {
    interface PixivnLabelIds {
        "sleep_1_hour": never;
        "nap_1_hour": never;
        "sleep": never;
        "nap": never;
        "start": never;
        "order_product": never;
        "talk_alice_sleep_result": never;
        "talk_alice_sleep": never;
        "talk_alice": never;
        "alice_talk_menu": never;
        "take_product": never;
    }
}
export const characterIds = ["mc","alice"] as const;
export const characterIdsEnum = {"mc":"mc","alice":"alice"} as const;
export const labelIds = ["sleep_1_hour","nap_1_hour","sleep","nap","start","order_product","talk_alice_sleep_result","talk_alice_sleep","talk_alice","alice_talk_menu","take_product"] as const;
export const labelIdsEnum = {"sleep_1_hour":"sleep_1_hour","nap_1_hour":"nap_1_hour","sleep":"sleep","nap":"nap","start":"start","order_product":"order_product","talk_alice_sleep_result":"talk_alice_sleep_result","talk_alice_sleep":"talk_alice_sleep","talk_alice":"talk_alice","alice_talk_menu":"alice_talk_menu","take_product":"take_product"} as const;
