// @ts-nocheck
/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
declare module "@drincs/pixi-vn/characters" {
    interface PixivnCharacterIds {
        "mc": never;
        "alice": never;
    }
}
declare module "@drincs/pixi-vn/narration" {
    interface PixivnLabelIds {
        "sleep-1-hour": never;
        "nap-1-hour": never;
        "sleep": never;
        "nap": never;
        "start": never;
        "order-product": never;
        "take-key": never;
        "talk-alice-sleep-result": never;
        "talk-alice-sleep": never;
        "talk-alice": never;
        "alice-talk-menu": never;
    }
}
export {};
