/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by @drincs/pixi-vn vite plugin. Do not edit manually.
declare module "@drincs/pixi-vn/characters" {
    interface PixivnCharacterIds {
        "mc": never;
        "alice": never;
    }
}
declare module "@drincs/pixi-vn/narration" {
    interface PixivnLabelIds {
        "sleep-1-hour": never;
        "nap-1-hour": never;
        "sleep": never;
        "nap": never;
        "start": never;
        "order-product": never;
        "take-key": never;
        "talk-alice-sleep-result": never;
        "talk-alice-sleep": never;
        "talk-alice": never;
        "alice-talk-menu": never;
    }
}
export const characterIds = ["mc","alice"] as const;
export const characterIdsEnum = {"mc":"mc","alice":"alice"} as const;
export const labelIds = ["sleep-1-hour","nap-1-hour","sleep","nap","start","order-product","take-key","talk-alice-sleep-result","talk-alice-sleep","talk-alice","alice-talk-menu"] as const;
export const labelIdsEnum = {"sleep-1-hour":"sleep-1-hour","nap-1-hour":"nap-1-hour","sleep":"sleep","nap":"nap","start":"start","order-product":"order-product","take-key":"take-key","talk-alice-sleep-result":"talk-alice-sleep-result","talk-alice-sleep":"talk-alice-sleep","talk-alice":"talk-alice","alice-talk-menu":"alice-talk-menu"} as const;
