/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as NarrationRouteImport } from './routes/narration'
import { Route as GameRouteImport } from './routes/game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameNavigationRouteImport } from './routes/game/navigation'
import { Route as GameNarrationRouteImport } from './routes/game/narration'
import { Route as GameMapRouteImport } from './routes/game/map'

const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrationRoute = NarrationRouteImport.update({
  id: '/narration',
  path: '/narration',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNavigationRoute = GameNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => GameRoute,
} as any)
const GameNarrationRoute = GameNarrationRouteImport.update({
  id: '/narration',
  path: '/narration',
  getParentRoute: () => GameRoute,
} as any)
const GameMapRoute = GameMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/narration': typeof NarrationRoute
  '/navigation': typeof NavigationRoute
  '/game/map': typeof GameMapRoute
  '/game/narration': typeof GameNarrationRoute
  '/game/navigation': typeof GameNavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/narration': typeof NarrationRoute
  '/navigation': typeof NavigationRoute
  '/game/map': typeof GameMapRoute
  '/game/narration': typeof GameNarrationRoute
  '/game/navigation': typeof GameNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game': typeof GameRouteWithChildren
  '/narration': typeof NarrationRoute
  '/navigation': typeof NavigationRoute
  '/game/map': typeof GameMapRoute
  '/game/narration': typeof GameNarrationRoute
  '/game/navigation': typeof GameNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/narration'
    | '/navigation'
    | '/game/map'
    | '/game/narration'
    | '/game/navigation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/narration'
    | '/navigation'
    | '/game/map'
    | '/game/narration'
    | '/game/navigation'
  id:
    | '__root__'
    | '/'
    | '/game'
    | '/narration'
    | '/navigation'
    | '/game/map'
    | '/game/narration'
    | '/game/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRoute: typeof GameRouteWithChildren
  NarrationRoute: typeof NarrationRoute
  NavigationRoute: typeof NavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narration': {
      id: '/narration'
      path: '/narration'
      fullPath: '/narration'
      preLoaderRoute: typeof NarrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/navigation': {
      id: '/game/navigation'
      path: '/navigation'
      fullPath: '/game/navigation'
      preLoaderRoute: typeof GameNavigationRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/narration': {
      id: '/game/narration'
      path: '/narration'
      fullPath: '/game/narration'
      preLoaderRoute: typeof GameNarrationRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/map': {
      id: '/game/map'
      path: '/map'
      fullPath: '/game/map'
      preLoaderRoute: typeof GameMapRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameMapRoute: typeof GameMapRoute
  GameNarrationRoute: typeof GameNarrationRoute
  GameNavigationRoute: typeof GameNavigationRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameMapRoute: GameMapRoute,
  GameNarrationRoute: GameNarrationRoute,
  GameNavigationRoute: GameNavigationRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRoute: GameRouteWithChildren,
  NarrationRoute: NarrationRoute,
  NavigationRoute: NavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
